---
- hosts: containers
  connection: docker
  tasks:
    - name: Duplicated task name
      yum:
        name: chrony
        state: installed
      notify:
        - Restart chronyd

    - name: Duplicated task name
      replace: 
        dest: /etc/chrony.conf
        regexp: "0.centos.pool.ntp.org"
        replace: "{{ ntp_server }}"
      notify:
        - Restart chronyd

  vars:
    ntp_server: ntp1.jst.mfeed.ad.jp

  handlers:
    - name: Restart chronyd
      systemd:
        name: chronyd
        state: restarted
    - name: Restart chronyd
      debug:
        msg: hello
