#!/bin/bash

container_name=test01
image_name=centos

echo Checking container...

docker inspect ${container_name} > /dev/null
if [[ $? = 0 ]]; then
	docker rm -f ${container_name} > /dev/null
	echo Removed old ${container_name}
fi

echo Starting container...
docker run --privileged -d --name ${container_name} ${image_name} /sbin/init > /dev/null
echo ${container_name} is runnning on $(docker inspect ${container_name} -f '{{.NetworkSettings.IPAddress}}')
