---
- hosts: containers
  connection: docker
  tasks:
    - name: Backup epel repo config
      copy:
        remote_src: True
        src: /etc/yum.repos.d/epel.repo
        dest: /etc/yum.repos.d/epel.repo.default
        force: no
    
    # Check requirements of modifying
    - name: Compute epel.repo MD5
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: stat_current
    
    - name: Compute epel.repo.default MD5
      stat:
        path: /etc/yum.repos.d/epel.repo.default
      register: stat_default
    
    - name: Modify epel's priorities
      command: "perl -pi -e 's|^gpgcheck=.*|$&\npriority=9|' /etc/yum.repos.d/epel.repo"
      when: stat_current.stat.md5 == stat_default.stat.md5

